# Generated by Django 3.0.7 on 2020-06-04 16:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='anonymous', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0c486b31-d694-4a2b-b278-277780b2abf0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3c8efab2-afc3-44fa-a6bc-3b62f5c16b91'), editable=False, primary_key=True, serialize=False),
        ),
    ]
