# Generated by Django 3.0.7 on 2020-06-08 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200604_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='isActif',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.UUID('08f475f8-d9a0-449b-b943-daacbaec4e16'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dbcbf022-c4ab-40f3-b829-1de210b80edc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
