# Generated by Django 3.0.6 on 2020-05-09 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank='False', default='', max_length=100)),
                ('startAt', models.DateTimeField()),
                ('endAt', models.DateTimeField()),
                ('storageAccount', models.CharField(blank=True, max_length=24)),
                ('storageKey', models.CharField(blank=True, max_length=100)),
                ('followers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(blank=True, to='photos.Photo')),
            ],
            options={
                'ordering': ['startAt'],
            },
        ),
    ]
